#!/usr/bin/env python3
"""
Load Users from JSON

Creates users in Supabase Auth from a JSON configuration file.
"""

import asyncio
import json
import sys
import argparse
from pathlib import Path
from typing import Dict, List

# Fix Windows console encoding for emoji support
if sys.platform == "win32":
    import io

    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

# Add backend to path
backend_dir = Path(__file__).parent.parent.parent
sys.path.insert(0, str(backend_dir))

try:
    from database.connection import db_connection
except ImportError:
    from backend.database.connection import db_connection


SYSTEM_USER_ID = "00000000-0000-0000-0000-000000000001"


async def load_users(json_file: str):
    """
    Load users from JSON file

    Args:
        json_file: Path to JSON file containing users
    """
    print("=" * 60)
    print("LOAD USERS FROM JSON")
    print("=" * 60)

    # Load JSON file
    json_path = Path(json_file)
    if not json_path.exists():
        print(f"\n❌ Error: File not found: {json_file}")
        return

    print(f"\n📂 Loading file: {json_file}")
    try:
        with open(json_path, "r") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"\n❌ Error: Invalid JSON: {e}")
        return
    except Exception as e:
        print(f"\n❌ Error reading file: {e}")
        return

    # Validate structure
    if "users" not in data:
        print("\n❌ Error: JSON must contain 'users' array")
        return

    users = data["users"]
    if not isinstance(users, list):
        print("\n❌ Error: 'users' must be an array")
        return

    print(f"\n📋 Found {len(users)} user(s) to create")

    # Process each user
    created = 0
    skipped = 0
    failed = 0

    for i, user in enumerate(users, 1):
        user_id = user.get("id")
        email = user.get("email")
        password = user.get("password")

        print(f"\n[{i}/{len(users)}] Processing: {email}")

        # Validate required fields
        if not all([user_id, email, password]):
            print(f"  ✗ Missing required fields (id, email, password)")
            failed += 1
            continue

        # Check if user is system user
        if user_id == SYSTEM_USER_ID:
            print(f"  ⚠️  Skipped: Cannot create system user")
            skipped += 1
            continue

        try:
            # Use the service client to access auth admin functions
            auth_client = db_connection.service_client.auth.admin

            # Try to create the user using Auth Admin API
            print(f"  ℹ️  User ID: {user_id}")
            print(f"  📧 Email: {email}")

            try:
                response = auth_client.create_user(
                    {
                        "email": email,
                        "password": password,
                        "email_confirm": True,  # Auto-confirm email
                        "user_metadata": {"created_by": "load_users_script"},
                    }
                )

                # Note: The created user ID will be auto-generated by Supabase
                # We can't set a custom ID directly
                actual_user_id = response.user.id if response.user else None

                if actual_user_id:
                    print(f"  ✅ Created user with ID: {actual_user_id}")
                    if actual_user_id != user_id:
                        print(
                            f"  ⚠️  Warning: Created ID ({actual_user_id}) differs from JSON ID ({user_id})"
                        )
                        print(f"      Update your test_users.json with the actual ID!")
                    created += 1
                else:
                    print(f"  ✗ Failed: No user ID returned")
                    failed += 1

            except Exception as auth_error:
                error_msg = str(auth_error)
                if (
                    "already registered" in error_msg.lower()
                    or "duplicate" in error_msg.lower()
                ):
                    print(f"  ⚠️  Skipped: User already exists")
                    # Try to get the existing user ID
                    try:
                        list_response = auth_client.list_users()
                        for existing_user in list_response:
                            if existing_user.email == email:
                                print(f"      Existing User ID: {existing_user.id}")
                                if existing_user.id != user_id:
                                    print(f"      Update JSON with this ID!")
                                break
                    except Exception as list_error:
                        print(f"      (Could not retrieve user ID: {list_error})")
                    skipped += 1
                else:
                    print(f"  ✗ Auth Error: {error_msg}")
                    failed += 1

        except Exception as e:
            print(f"  ✗ Error: {e}")
            failed += 1

    # Summary
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"  Total users: {len(users)}")
    print(f"  Created: {created}")
    print(f"  Skipped: {skipped}")
    print(f"  Failed: {failed}")

    if created > 0:
        print("\n✅ Users created successfully!")
        print("\n⚠️  IMPORTANT: Update test_users.json with actual user IDs")
        print("  The IDs generated by Supabase may differ from those in the JSON file.")

    if failed == 0 and created + skipped == len(users):
        print("\n✅ Load users complete!")
        if created > 0:
            print("\nNext steps:")
            print(f"  1. Update test_users.json with actual user IDs (if they differ)")
            print(f"  2. Run: python scripts\\db\\load_entries.py")
        else:
            print("\nNext step:")
            print(f"  python scripts\\db\\load_entries.py")
    elif failed > 0:
        print(f"\n⚠️  {failed} user(s) failed to create")


def main():
    """Main entry point"""
    # Default path to JSON file in data directory
    default_json = Path(__file__).parent / "data" / "test_users.json"

    parser = argparse.ArgumentParser(description="Load users from JSON file")
    parser.add_argument(
        "json_file",
        nargs="?",
        default=str(default_json),
        help=f"Path to JSON file containing users (default: {default_json})",
    )

    args = parser.parse_args()

    asyncio.run(load_users(args.json_file))


if __name__ == "__main__":
    main()
